/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eiW1BLrkDJY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Poppins } from 'next/font/google'
import { Arimo } from 'next/font/google'

poppins({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function AffiliateProgram() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <DumbbellIcon className="h-6 w-6" />
          <span className="sr-only">Fitness Tracker</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Features
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Pricing
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Affiliate
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  Earn with our Affiliate Program
                </h1>
                <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  Join our affiliate program and start earning commissions by promoting our fitness tracker to your
                  audience.
                </p>
                <Button>Join Now</Button>
              </div>
              <img
                src="/placeholder.svg"
                width="600"
                height="400"
                alt="Affiliate Program"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="grid gap-12 lg:grid-cols-2 lg:gap-24">
              <div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Affiliate Program Details</h2>
                <div className="mt-6 space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Commission Rates</h3>
                    <p className="text-muted-foreground">Earn up to 20% commission on every sale you refer.</p>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">Payment Terms</h3>
                    <p className="text-muted-foreground">Get paid monthly via PayPal or direct bank transfer.</p>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold">How to Join</h3>
                    <p className="text-muted-foreground">
                      Sign up on our website and get access to your unique affiliate link to start promoting.
                    </p>
                  </div>
                </div>
                <Button variant="outline" className="mt-6">
                  Sign Up Now
                </Button>
              </div>
              <div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">What Our Affiliates Say</h2>
                <div className="mt-6 space-y-6">
                  <div className="grid gap-4">
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="text-lg font-medium">
                          "The Fitness Tracker affiliate program has been a\n game-changer for my business. The
                          commission rates\n are great, and the support team is always\n responsive."
                        </p>
                        <p className="text-sm text-muted-foreground">- John Doe, Fitness Blogger</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>SM</AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="text-lg font-medium">
                          "I've been an affiliate for Fitness Tracker for\n over a year, and it's been a fantastic
                          experience.\n The product is great, and the commissions have\n really helped grow my
                          business."
                        </p>
                        <p className="text-sm text-muted-foreground">- Sarah Miller, Health Coach</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 text-center">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Join Our Affiliate Program</h2>
              <p className="max-w-[600px] mx-auto text-muted-foreground md:text-xl">
                Start earning commissions by promoting our fitness tracker to your audience.
              </p>
              <Button>Sign Up Now</Button>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
            <Link href="#" prefetch={false}>
              About Us
            </Link>
            <Link href="#" prefetch={false}>
              Our Team
            </Link>
            <Link href="#" prefetch={false}>
              Careers
            </Link>
            <Link href="#" prefetch={false}>
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
            <Link href="#" prefetch={false}>
              Fitness Tracker
            </Link>
            <Link href="#" prefetch={false}>
              Smartwatch
            </Link>
            <Link href="#" prefetch={false}>
              Accessories
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Blog
            </Link>
            <Link href="#" prefetch={false}>
              Documentation
            </Link>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              FAQs
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
            <Link href="#" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" prefetch={false}>
              Cookie Policy
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Affiliate</h3>
            <Link href="#" prefetch={false}>
              Program Details
            </Link>
            <Link href="#" prefetch={false}>
              Become an Affiliate
            </Link>
            <Link href="#" prefetch={false}>
              Affiliate Dashboard
            </Link>
            <Link href="#" prefetch={false}>
              Affiliate FAQ
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}
