/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LYan6eWr34V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function BookDemo() {
  return (
    <Card className="max-w-md mx-auto p-6 sm:p-8">
      <CardHeader>
        <CardTitle>Book a Demo</CardTitle>
        <CardDescription>Fill out the form to schedule a demo of our gym management system.</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="Enter your email" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="phone">Phone Number</Label>
            <Input id="phone" type="tel" placeholder="Enter your phone number" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="features">Features of Interest</Label>
            <Select id="features" multiple>
              <SelectTrigger>
                <SelectValue placeholder="Select features" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="gym-membership">Gym Membership Management</SelectItem>
                  <SelectItem value="class-scheduling">Class Scheduling</SelectItem>
                  <SelectItem value="personal-training">Personal Training</SelectItem>
                  <SelectItem value="reporting">Reporting and Analytics</SelectItem>
                  <SelectItem value="billing">Billing and Invoicing</SelectItem>
                  <SelectItem value="crm">CRM and Member Management</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
        </form>
      </CardContent>
      <CardFooter>
        <Button type="submit" className="w-full">
          Book Demo
        </Button>
      </CardFooter>
    </Card>
  )
}
