/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Vw0yWAQQnyd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function PrivatePolicy() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Privacy Policy</h1>
          <p className="mt-4 text-muted-foreground">
            At our event management website, we are committed to protecting the privacy and security of your personal
            information. This privacy policy outlines how we collect, use, and safeguard your data to ensure a
            transparent and trustworthy experience.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Collection</h2>
          <p className="mt-4 text-muted-foreground">
            We collect personal information, such as your name, email address, and contact details, when you register
            for an event or create an account on our platform. We may also collect information about your event
            preferences, attendance history, and any feedback or inquiries you provide.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Usage</h2>
          <p className="mt-4 text-muted-foreground">
            We use the collected data to provide you with the best possible event experience, including sending you
            updates, managing event registrations, and improving our services. We may also use your information for
            marketing purposes, such as sending you newsletters or promotional offers, but you can opt-out of these
            communications at any time.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Sharing</h2>
          <p className="mt-4 text-muted-foreground">
            We may share your personal information with third-party service providers, such as event venues or catering
            companies, to facilitate the organization and delivery of the events you attend. We will only share the
            necessary information and ensure that these third parties adhere to the same privacy and security standards
            as our own.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Security</h2>
          <p className="mt-4 text-muted-foreground">
            We take the security of your personal information very seriously and have implemented robust measures to
            protect it from unauthorized access, modification, or disclosure. This includes the use of encryption,
            secure servers, and regular security audits.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Your Rights</h2>
          <p className="mt-4 text-muted-foreground">
            You have the right to access, update, and delete your personal information at any time. You can also request
            a copy of the data we hold about you and object to the processing of your data for certain purposes. If you
            have any concerns or questions about our privacy practices, please don't hesitate to contact us.
          </p>
        </div>
      </div>
    </div>
  )
}
