/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2fBwDdxC5hJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Register() {
  return (
    <div className="flex flex-col min-h-dvh">
      <section className="w-full py-12 md:py-24 lg:py-32 border-b">
        <div className="container px-4 md:px-6 space-y-6 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Annual Developer Conference</h1>
            <p className="text-muted-foreground md:text-xl">June 15-17, 2024 | San Francisco, CA</p>
          </div>
          <div className="flex justify-center">
            <Button className="px-8">Register Now</Button>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <Card className="max-w-4xl mx-auto p-6 sm:p-8 md:p-10">
            <CardHeader>
              <CardTitle className="text-3xl font-bold">Event Registration</CardTitle>
              <CardDescription>Fill out the form below to register for the event.</CardDescription>
            </CardHeader>
            <CardContent>
              <form className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="grid gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="name" className="text-sm font-medium">
                      Name
                    </Label>
                    <Input id="name" placeholder="John Doe" required />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="email" className="text-sm font-medium">
                      Email
                    </Label>
                    <Input id="email" type="email" placeholder="john@example.com" required />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="company" className="text-sm font-medium">
                      Company
                    </Label>
                    <Input id="company" placeholder="Acme Inc" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="job-title" className="text-sm font-medium">
                      Job Title
                    </Label>
                    <Input id="job-title" placeholder="Software Engineer" />
                  </div>
                </div>
                <div className="grid gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="dietary-requirements" className="text-sm font-medium">
                      Dietary Requirements
                    </Label>
                    <Textarea
                      id="dietary-requirements"
                      placeholder="Please let us know if you have any dietary restrictions or allergies."
                    />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="accommodations" className="text-sm font-medium">
                      Special Accommodations
                    </Label>
                    <Textarea
                      id="accommodations"
                      placeholder="Please let us know if you require any special accommodations."
                    />
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter>
              <div className="flex justify-end">
                <Button type="submit">Register</Button>
              </div>
            </CardFooter>
          </Card>
        </div>
      </section>
    </div>
  )
}
