/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JpX8Puv2KRT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"

export function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 md:px-10 lg:px-16">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-2xl font-bold" prefetch={false}>
            MoviePlex
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Movies
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Theaters
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Deals
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Sign In
            </Link>
            <Button variant="secondary">Sign Up</Button>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-muted py-10 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-10 lg:px-16">
            <Carousel>
              <CarouselContent>
                <CarouselItem>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                    <div>
                      <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">Avengers: Endgame</h1>
                      <p className="text-muted-foreground mb-6">The epic conclusion to the Avengers saga.</p>
                      <div className="flex space-x-4">
                        <Button>Buy Tickets</Button>
                        <Button variant="secondary">Watch Trailer</Button>
                      </div>
                    </div>
                    <img
                      src="/placeholder.svg"
                      width={600}
                      height={400}
                      alt="Avengers: Endgame"
                      className="rounded-lg object-cover"
                      style={{ aspectRatio: "600/400", objectFit: "cover" }}
                    />
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                    <div>
                      <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-4">Dune</h1>
                      <p className="text-muted-foreground mb-6">An epic science fiction film.</p>
                      <div className="flex space-x-4">
                        <Button>Buy Tickets</Button>
                        <Button variant="secondary">Watch Trailer</Button>
                      </div>
                    </div>
                    <img
                      src="/placeholder.svg"
                      width={600}
                      height={400}
                      alt="Dune"
                      className="rounded-lg object-cover"
                      style={{ aspectRatio: "600/400", objectFit: "cover" }}
                    />
                  </div>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </section>
        <section className="py-10 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-10 lg:px-16">
            <div className="mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-2">Search Movies</h2>
              <p className="text-muted-foreground">Find the perfect movie for your next night out.</p>
            </div>
            <form className="flex items-center space-x-4">
              <Input
                type="text"
                placeholder="Search movies, genres, or theaters"
                className="flex-1 rounded-lg px-4 py-2 bg-muted text-muted-foreground"
              />
              <Button>Search</Button>
            </form>
          </div>
        </section>
        <section className="py-10 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-10 lg:px-16">
            <div className="mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-2">Now Showing</h2>
              <p className="text-muted-foreground">Check out the latest movies in theaters now.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[1, 2, 3, 4, 5, 6, 7, 8].map((item) => (
                <Card key={item}>
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={450}
                    alt={`Movie ${item}`}
                    className="rounded-t-lg object-cover"
                    style={{ aspectRatio: "300/450", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-lg font-bold mb-2">Movie {item}</h3>
                    <p className="text-muted-foreground mb-4">A brief description of the movie.</p>
                    <div className="flex justify-between items-center">
                      <Button>Buy Tickets</Button>
                      <Button variant="secondary">Watch Trailer</Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
        <section className="py-10 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-10 lg:px-16">
            <div className="mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-2">Upcoming</h2>
              <p className="text-muted-foreground">Check out the latest upcoming movies.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[1, 2, 3, 4, 5, 6, 7, 8].map((item) => (
                <Card key={item}>
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={450}
                    alt={`Movie ${item}`}
                    className="rounded-t-lg object-cover"
                    style={{ aspectRatio: "300/450", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-lg font-bold mb-2">Movie {item}</h3>
                    <p className="text-muted-foreground mb-4">A brief description of the movie.</p>
                    <div className="flex justify-between items-center">
                      <Button>Set Reminder</Button>
                      <Button variant="secondary">Watch Trailer</Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
        <section className="py-10 md:py-16 lg:py-24">
          <div className="container mx-auto px-6 md:px-10 lg:px-16">
            <div className="mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-2">Top Rated</h2>
              <p className="text-muted-foreground">Check out the highest-rated movies.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {[1, 2, 3, 4, 5, 6, 7, 8].map((item) => (
                <Card key={item}>
                  <img
                    src="/placeholder.svg"
                    width={300}
                    height={450}
                    alt={`Movie ${item}`}
                    className="rounded-t-lg object-cover"
                    style={{ aspectRatio: "300/450", objectFit: "cover" }}
                  />
                  <CardContent className="p-4">
                    <h3 className="text-lg font-bold mb-2">Movie {item}</h3>
                    <p className="text-muted-foreground mb-4">A brief description of the movie.</p>
                    <div className="flex justify-between items-center">
                      <Button>Buy Tickets</Button>
                      <Button variant="secondary">Watch Trailer</Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6 md:px-10 lg:px-16">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="mb-4 md:mb-0">
            <Link href="#" className="text-2xl font-bold" prefetch={false}>
              MoviePlex
            </Link>
          </div>
          <div className="flex items-center space-x-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              My Bookings
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Showtimes
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
