/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NcfeHuHJLRU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function PrivacyPolicy() {
  return (
    <div className="w-full max-w-3xl mx-auto py-12 md:py-16 px-4 md:px-6">
      <header className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="text-muted-foreground mt-2">Effective Date: September 15, 2024</p>
      </header>
      <section className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold">What Personal Data We Collect</h2>
          <p className="text-muted-foreground mt-2">
            At Varni Consultancy, we collect the following personal data from our users:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>Name and email address when you sign up for our newsletter</li>
            <li>Contact information (name, email, phone number) when you reach out to us for consulting services</li>
            <li>Usage data, such as pages visited, links clicked, and time spent on our website</li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold">How We Use Your Personal Data</h2>
          <p className="text-muted-foreground mt-2">We use the personal data we collect for the following purposes:</p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>
              To provide you with the consulting services you have requested and to communicate with you about those
              services
            </li>
            <li>To send you our newsletter and other updates about our services, if you have signed up for them</li>
            <li>To improve our website and the services we offer based on usage data</li>
            <li>To comply with legal and regulatory requirements, such as accounting and tax obligations</li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold">How We Protect Your Personal Data</h2>
          <p className="text-muted-foreground mt-2">
            We take the security of your personal data seriously and have implemented the following measures to protect
            it:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>We use industry-standard encryption to protect data in transit and at rest</li>
            <li>
              We restrict access to your personal data to only those employees and third-party service providers who
              need it to perform their duties
            </li>
            <li>We regularly review and update our security practices to ensure they remain effective</li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Your Rights Regarding Your Personal Data</h2>
          <p className="text-muted-foreground mt-2">
            You have the following rights regarding the personal data we collect about you:
          </p>
          <ul className="list-disc pl-6 mt-2 space-y-2">
            <li>The right to access, correct, or delete the personal data we have about you</li>
            <li>The right to object to or restrict the processing of your personal data</li>
            <li>
              The right to data portability, which means you can request a copy of your personal data in a structured,
              commonly used, and machine-readable format
            </li>
            <li>
              The right to lodge a complaint with a supervisory authority if you believe we have not handled your
              personal data in accordance with data protection laws
            </li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Contact Us</h2>
          <p className="text-muted-foreground mt-2">
            If you have any questions or concerns about our privacy practices, please contact our Data Protection
            Officer at:
          </p>
          <div className="mt-2 space-y-1">
            <p>Varni Consultancy</p>
            <p>Attn: Data Protection Officer</p>
            <p>123 Main Street</p>
            <p>Anytown, USA 12345</p>
            <p>Email: privacy@varniconsultancy.com</p>
          </div>
        </div>
      </section>
    </div>
  )
}
