/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xTn06FdpPE2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Registration() {
  return (
    <div className="flex h-screen items-center justify-center bg-background">
      <Card className="w-full max-w-md">
        <div className="flex justify-center py-6">
          <img
            src="/placeholder.svg"
            alt="Varni Consultancy"
            width={120}
            height={40}
            style={{ aspectRatio: "120/40", objectFit: "cover" }}
          />
        </div>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="example@email.com" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" />
          </div>
          <Button className="w-full">Register</Button>
        </CardContent>
        <CardFooter className="text-center text-muted-foreground">
          Already have an account?{" "}
          <Link href="#" className="font-medium underline" prefetch={false}>
            Login
          </Link>
        </CardFooter>
      </Card>
    </div>
  )
}
