/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HlADljTTM2w
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TermsOfServices() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 md:px-6 md:py-16 lg:px-8 lg:py-20">
      <div className="space-y-8">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
        <section>
          <h2 className="text-2xl font-bold">Introduction</h2>
          <p className="mt-4 text-muted-foreground">
            Welcome to the Terms of Service for Varni Consultancy. These terms govern your use of our services and
            website. By accessing or using our platform, you agree to be bound by these terms and our Privacy Policy.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">User Eligibility</h2>
          <p className="mt-4 text-muted-foreground">
            Our services are intended for use by individuals aged 18 and above. By using our platform, you represent and
            warrant that you are at least 18 years old and have the legal capacity to enter into a binding agreement.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">User Responsibilities</h2>
          <p className="mt-4 text-muted-foreground">
            As a user of our platform, you are responsible for maintaining the confidentiality of your account and
            password, and for restricting access to your computer. You agree to be responsible for all activities that
            occur under your account.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Intellectual Property</h2>
          <p className="mt-4 text-muted-foreground">
            The content, design, and functionality of our platform are the property of Varni Consultancy and are
            protected by copyright, trademark, and other intellectual property laws. You may not modify, copy,
            distribute, transmit, display, reproduce, or create derivative works from our platform without our prior
            written consent.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Confidentiality</h2>
          <p className="mt-4 text-muted-foreground">
            During your use of our platform, you may have access to confidential information. You agree to maintain the
            confidentiality of such information and not to disclose or use it for any purpose other than as necessary to
            use our services.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Limitation of Liability</h2>
          <p className="mt-4 text-muted-foreground">
            Varni Consultancy shall not be liable for any indirect, special, incidental, or consequential damages
            arising out of or related to your use of our platform. Our total liability shall not exceed $100. Some
            jurisdictions do not allow the exclusion or limitation of certain damages, so these limitations may not
            apply to you.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Termination</h2>
          <p className="mt-4 text-muted-foreground">
            We reserve the right to suspend or terminate your access to our platform at any time for any reason,
            including if we reasonably believe you have violated these terms. You may also terminate your account at any
            time by contacting us.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Governing Law</h2>
          <p className="mt-4 text-muted-foreground">
            These terms shall be governed by and construed in accordance with the laws of [Jurisdiction], without giving
            effect to any principles of conflicts of law.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-bold">Contact Information</h2>
          <p className="mt-4 text-muted-foreground">
            If you have any questions or concerns about these terms, please contact us at:
          </p>
          <p className="mt-2 text-muted-foreground">
            Varni Consultancy
            <br />
            123 Main Street
            <br />
            Anytown, USA 12345
            <br />
            Email: info@varniconsultancy.com
          </p>
        </section>
      </div>
    </div>
  )
}
