/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zwTPSaNNy0y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Testimonials() {
  return (
    <div className="flex flex-col">
      <section className="bg-primary py-12 md:py-16 lg:py-20">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-3xl font-bold tracking-tighter text-primary-foreground sm:text-4xl md:text-5xl">
              Trusted by Businesses Worldwide
            </h1>
            <p className="mt-4 text-lg text-primary-foreground md:text-xl">
              Varni Consultancy has helped countless businesses achieve their goals through our expert services and
              unwavering commitment to customer satisfaction.
            </p>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-16 lg:py-20">
        <div className="container grid grid-cols-1 gap-6 px-4 md:grid-cols-2 md:gap-8 lg:grid-cols-3 lg:gap-10 xl:gap-12">
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Sarah Johnson" />
                <AvatarFallback>SJ</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Sarah Johnson</h3>
                <p className="text-sm text-muted-foreground">CEO, Acme Inc.</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Varni Consultancy's team provided exceptional service and\n guidance. They helped us streamline our
              operations and improve\n our bottom line."
            </blockquote>
          </div>
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Alex Smith" />
                <AvatarFallback>AS</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Alex Smith</h3>
                <p className="text-sm text-muted-foreground">CFO, XYZ Corporation</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Working with Varni Consultancy was a game-changer for our\n business. Their expertise and attention to
              detail were\n invaluable."
            </blockquote>
          </div>
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Emily Parker" />
                <AvatarFallback>EP</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Emily Parker</h3>
                <p className="text-sm text-muted-foreground">COO, Startup Inc.</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Varni Consultancy's team went above and beyond to understand\n our unique challenges and provide tailored
              solutions. We're\n thrilled with the results."
            </blockquote>
          </div>
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="John Doe" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">John Doe</h3>
                <p className="text-sm text-muted-foreground">VP of Operations, Mega Corp</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Varni Consultancy's expertise and attention to detail have\n been invaluable to our business. We highly
              recommend their\n services."
            </blockquote>
          </div>
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Jane Doe" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Jane Doe</h3>
                <p className="text-sm text-muted-foreground">Founder, Startup XYZ</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Varni Consultancy's team has been instrumental in helping us\n navigate the challenges of scaling our
              business. Their guidance\n has been invaluable."
            </blockquote>
          </div>
          <div className="rounded-lg border bg-background p-6 shadow-sm">
            <div className="flex items-start">
              <Avatar className="mr-4">
                <AvatarImage src="/placeholder-user.jpg" alt="Michael Johnson" />
                <AvatarFallback>MJ</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Michael Johnson</h3>
                <p className="text-sm text-muted-foreground">CTO, Tech Inc.</p>
              </div>
            </div>
            <blockquote className="mt-4 text-muted-foreground">
              "Varni Consultancy's team has a deep understanding of our\n industry and provided us with innovative
              solutions to improve\n our operations."
            </blockquote>
          </div>
        </div>
      </section>
    </div>
  )
}
